version: "3.9"
services:
  api:
    build: ./api
    container_name: plaidll-api
    env_file: ./infra/.env.example
    ports:
      - "8080:8080"
  worker:
    build: ./worker
    container_name: plaidll-worker
    environment:
      API_BASE: http://api:8080
    depends_on:
      - api
  web:
    build: ./web
    container_name: plaidll-web
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - api
